var COMPILED=true,goog=goog||{};goog.global=this;goog.DEBUG=true;goog.LOCALE="en";goog.evalWorksForGlobals_=null;goog.provide=function(a){if(!COMPILED){if(goog.getObjectByName(a)&&!goog.implicitNamespaces_[a])throw Error('Namespace "'+a+'" already declared.');for(var b=a;b=b.substring(0,b.lastIndexOf("."));)goog.implicitNamespaces_[b]=true}goog.exportPath_(a)};if(!COMPILED)goog.implicitNamespaces_={};
goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&goog.isDef(b))c[d]=b;else c=c[d]?c[d]:c[d]={}};goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(d[e])d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,f=0;d=b[f];f++){e.nameToPath[d]=a;a in e.pathToNames||(e.pathToNames[a]={});e.pathToNames[a][d]=true}for(d=0;b=c[d];d++){a in e.requires||(e.requires[a]={});e.requires[a][b]=true}}};
goog.require=function(a){if(!COMPILED)if(!goog.getObjectByName(a)){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=true;goog.writeScripts_()}else{a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){return a.instance_||(a.instance_=new a)}};
if(!COMPILED){goog.included_={};goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}};goog.inHtmlDocument_=function(){var a=goog.global.document;return typeof a!="undefined"&&"write"in a};goog.findBasePath_=function(){if(goog.inHtmlDocument_()){var a=goog.global.document;if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else{a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;--b){var c=a[b].src,d=c.length;if(c.substr(d-7)=="base.js"){goog.basePath=
c.substr(0,d-7);break}}}}};goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()&&!goog.dependencies_.written[a]){goog.dependencies_.written[a]=true;goog.global.document.write('<script type="text/javascript" src="'+a+'"><\/script>')}};goog.writeScripts_=function(){function a(f){if(!(f in d.written)){if(!(f in d.visited)){d.visited[f]=true;if(f in d.requires)for(var g in d.requires[f])if(g in d.nameToPath)a(d.nameToPath[g]);else if(!goog.getObjectByName(g))throw Error("Undefined nameToPath for "+
g);}if(!(f in c)){c[f]=true;b.push(f)}}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.writeScriptTag_(goog.basePath+b[e]);else throw Error("Undefined script input");};goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null};goog.findBasePath_();goog.global.CLOSURE_NO_DEPS||goog.writeScriptTag_(goog.basePath+"deps.js")}
goog.typeOf=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};goog.propertyIsEnumerableCustom_=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return true;return false};goog.propertyIsEnumerable_=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):goog.propertyIsEnumerableCustom_(a,b)};goog.isDef=function(a){return a!==undefined};goog.isNull=function(a){return a===null};
goog.isDefAndNotNull=function(a){return a!=null};goog.isArray=function(a){return goog.typeOf(a)=="array"};goog.isArrayLike=function(a){var b=goog.typeOf(a);return b=="array"||b=="object"&&typeof a.length=="number"};goog.isDateLike=function(a){return goog.isObject(a)&&typeof a.getFullYear=="function"};goog.isString=function(a){return typeof a=="string"};goog.isBoolean=function(a){return typeof a=="boolean"};goog.isNumber=function(a){return typeof a=="number"};
goog.isFunction=function(a){return goog.typeOf(a)=="function"};goog.isObject=function(a){a=goog.typeOf(a);return a=="object"||a=="array"||a=="function"};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36);goog.uidCounter_=0;
goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if(b=="object"||b=="array"){if(a.clone)return a.clone();b=b=="array"?[]:{};for(var c in a)b[c]=goog.cloneObject(a[c]);return b}return a};
goog.bind=function(a,b){var c=b||goog.global;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}};goog.partial=function(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}};
goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval){if(goog.evalWorksForGlobals_==null){goog.global.eval("var _et_ = 1;");if(typeof goog.global._et_!="undefined"){delete goog.global._et_;goog.evalWorksForGlobals_=true}else goog.evalWorksForGlobals_=false}if(goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=false;c.appendChild(b.createTextNode(a));
b.body.appendChild(c);b.body.removeChild(c)}}else throw Error("goog.globalEval not available");};goog.typedef=true;goog.getCssName=function(a,b){var c=a+(b?"-"+b:"");return goog.cssNameMapping_&&c in goog.cssNameMapping_?goog.cssNameMapping_[c]:c};goog.setCssNameMapping=function(a){goog.cssNameMapping_=a};goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};
goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b){var c=arguments.callee.caller;if(c.superClass_)return c.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var d=Array.prototype.slice.call(arguments,2),e=false,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===c)e=true;else if(e)return f.prototype[b].apply(a,d);if(a[b]===c)return a.constructor.prototype[b].apply(a,d);else throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};var crow={};crow.util={};crow.util.MonkeyPatches={};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c=this.length>>>0,d=Number(b)||0;d=d<0?Math.ceil(d):Math.floor(d);if(d<0)d+=c;for(;d<c;d++)if(d in this&&this[d]===a)return d;return-1};if(!Array.prototype.shuffle)Array.prototype.shuffle=function(){for(var a=this.concat(),b,c,d=a.length;d;b=parseInt(Math.random()*d),c=a[--d],a[d]=a[b],a[b]=c);return a};crow.Logger={};
(function(){var a={error:1,warn:2,info:3,debug:4,off:-Infinity},b=goog.global.console?console:{},c=a.warn;crow.Logger=function(d){this.klass=d};crow.Logger.prototype.getLogLevel=function(){return typeof this.klass.LOG_LEVEL!=="undefined"?this.klass.LOG_LEVEL:c};crow.Logger.prototype.error=function(){var d=Array.prototype.slice.call(arguments,0);d[0]="Crow Error: "+d[0];b&&b.error&&this.getLogLevel()>=1&&b.error.apply(b,d)};crow.Logger.prototype.warn=function(){var d=Array.prototype.slice.call(arguments,0);
d[0]="Crow Warning: "+d[0];b&&b.warn&&this.getLogLevel()>=2&&b.warn.apply(b,d)};crow.Logger.prototype.info=function(){var d=Array.prototype.slice.call(arguments,0);d[0]="Crow Info: "+d[0];b&&b.info&&this.getLogLevel()>=3&&b.info.apply(b,d)};crow.Logger.prototype.debug=function(){var d=Array.prototype.slice.call(arguments,0);d[0]="Crow Debug: "+d[0];b&&b.debug&&this.getLogLevel()>=4&&b.debug.apply(b,d)};crow.Logger.prototype.setLevel=function(d){return crow.Logger.setLevel(d,this.klass)};crow.Logger.setLevel=
function(d,e){var f=a[d.toLowerCase()];if(typeof f!=="number")throw Error("Invalid log level: "+d);if(e)e.LOG_LEVEL=f;else c=f};crow.Logger.setAppender=function(d){b=d}})();crow.util.Assert={};crow.assert=function(a,b){if(!a)throw Error(b);};crow.assert.InvalidArgumentType=function(a){return"Invalid argument type, expected "+a};crow.assert.IncorrectArgumentCount=function(a,b){return"Incorrect argument count, got "+a+" but expected "+b};crow.assert.IndexOutBounds=function(a){return"Index out of bounds (<0 or >length), was "+a};crow.assert.AbstractMethod=function(a){return"Method "+a+" is abstract; must be overridden"};
crow.assert.IllegalMethodCall=function(a,b){return"Method `"+a+"` cannot be called here: "+b};crow.structs={};crow.structs.BucketPriorityQueue=function(a){this.arr=[];this.length=0;this.key_comparator=a?a:crow.structs.BucketPriorityQueue.DEFAULT_KEY_COMPARATOR};crow.structs.BucketPriorityQueue.DEFAULT_KEY_COMPARATOR=function(a,b){if(a<b)return-1;if(a>b)return 1;return 0};crow.structs.BucketPriorityQueue.REVERSE_KEY_COMPARATOR=function(a,b){if(b<a)return-1;if(b>a)return 1;return 0};crow.structs.BucketPriorityQueue.prototype.enqueue=function(a,b){this.findBucket(a,true).push(b);this.length++};
crow.structs.BucketPriorityQueue.prototype.dequeue=function(){var a;if(this.length){var b=this.arr[0];a=b.shift();b.length||this.arr.shift();this.length--}return a};crow.structs.BucketPriorityQueue.prototype.contains=function(a,b){if(b)throw Error("not implemented yet");else for(var c=0;c<this.arr.length;c++)for(var d=this.arr[c],e=0;e<d.length;e++)if(d[e]==a)return true;return false};
crow.structs.BucketPriorityQueue.prototype.getPriority=function(a){for(var b=0;b<this.arr.length;b++)for(var c=this.arr[b],d=0;d<c.length;d++)if(c[d]==a)return c.key;return null};crow.structs.BucketPriorityQueue.prototype.remove=function(a,b){if(b)throw Error("not implemented yet");else for(var c=0;c<this.arr.length;c++)for(var d=this.arr[c],e=0;e<d.length;e++){var f=d[e];if(f==a){d.splice(e,1);d.length||this.arr.splice(c,1);this.length--;return f}}};
crow.structs.BucketPriorityQueue.prototype.peek=function(){if(this.length)return this.arr[0][0]};crow.structs.BucketPriorityQueue.prototype.peekKey=function(){if(this.length)return this.arr[0].key};crow.structs.BucketPriorityQueue.prototype.each=function(a){for(var b=0;b<this.arr.length;b++){var c=this.arr[b];if(c)for(var d=0;d<c.length;d++)a(c[d],b)}};
crow.structs.BucketPriorityQueue.prototype.findBucket=function(a,b){for(var c,d=this.key_comparator,e=0,f=this.arr.length-1,g,h;e<=f;){g=e+Math.floor((f-e)/2);var i=this.arr[g];h=d(i.key,a);if(h<0)e=g+1;else if(h>0)f=g-1;else{c=i;break}}if(!c&&b){c=[];c.key=a;e=false;for(g=g;g<this.arr.length&&!e;g++)if(d(this.arr[g].key,a)>0){this.arr.splice(g,0,c);e=true}e||this.arr.push(c)}return c};crow.Algorithm=function(){};crow.Algorithm.wrapperNodeGetterTemplate=function(a){return function(b){if(b instanceof a)return b;var c=this.wrapperNode.get(b);if(c)return c;c=new a(b);c.algorithm=this;this.wrapperNode.set(b,c);return c}};crow.Algorithm.prototype._invalidatePoint=function(a,b){for(var c=b.x,d=b.y,e=0;e<a.nodes.length;e++){var f=a.nodes[e];if(f.x==c&&f.y==d){a.nodes=a.nodes.slice(0,1);a.end=null;a.found=false;break}}};
crow.Algorithm.prototype._invalidateRegion=function(a,b){for(var c=b.x,d=b.y,e=c+b.dx,f=d+b.dy,g=0;g<a.nodes.length;g++){var h=a.nodes[g],i=h.x;h=h.y;if(i>=c&&h>=d&&i<e&&h<f){a.nodes=a.nodes.slice(0,1);a.end=null;a.found=false;break}}};crow.Algorithm.prototype.continueCalculating=function(a,b){var c=a.nodes[a.nodes.length-1];if(!c)c=a.start;var d={};if(b)d.limit=b;if(a.actor)d.actor=a.actor;c=this.findPath(c,a.goal,d);a.nodes=a.nodes.concat(c.nodes.slice(1));a.found=c.found;return a.found};
crow.Algorithm.NodeMap=function(a){var b={};this.get=function(c){c=b[c.id];return typeof c!=="undefined"?c:a};this.set=function(c,d){b[c.id]=d}};crow.Algorithm.PriorityQueue=function(){throw Error("A PriorityQueue class is required, but none found!");};crow.Algorithm.initializeDataStructures=function(){crow.Algorithm.PriorityQueue=crow.structs.BucketPriorityQueue;crow.Algorithm.initializeDataStructures=function(){}};goog.Disposable=function(){};goog.Disposable.prototype.disposed_=false;goog.Disposable.prototype.isDisposed=function(){return this.disposed_};goog.Disposable.prototype.getDisposed=goog.Disposable.prototype.isDisposed;goog.Disposable.prototype.dispose=function(){if(!this.disposed_){this.disposed_=true;this.disposeInternal()}};goog.Disposable.prototype.disposeInternal=function(){};goog.dispose=function(a){a&&typeof a.dispose=="function"&&a.dispose()};goog.debug={};goog.debug.Error=function(a){this.stack=Error().stack||"";if(a)this.message=String(a)};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.string={};goog.string.Unicode={NBSP:"\u00a0"};goog.string.startsWith=function(a,b){return a.lastIndexOf(b,0)==0};goog.string.endsWith=function(a,b){var c=a.length-b.length;return c>=0&&a.indexOf(b,c)==c};goog.string.caseInsensitiveStartsWith=function(a,b){return goog.string.caseInsensitiveCompare(b,a.substr(0,b.length))==0};goog.string.caseInsensitiveEndsWith=function(a,b){return goog.string.caseInsensitiveCompare(b,a.substr(a.length-b.length,b.length))==0};
goog.string.subs=function(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a};goog.string.collapseWhitespace=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};goog.string.isEmpty=function(a){return/^[\s\xa0]*$/.test(a)};goog.string.isEmptySafe=function(a){return goog.string.isEmpty(goog.string.makeSafe(a))};goog.string.isBreakingWhitespace=function(a){return!/[^\t\n\r ]/.test(a)};goog.string.isAlpha=function(a){return!/[^a-zA-Z]/.test(a)};
goog.string.isNumeric=function(a){return!/[^0-9]/.test(a)};goog.string.isAlphaNumeric=function(a){return!/[^a-zA-Z0-9]/.test(a)};goog.string.isSpace=function(a){return a==" "};goog.string.isUnicodeChar=function(a){return a.length==1&&a>=" "&&a<="~"||a>="\u0080"&&a<="\ufffd"};goog.string.stripNewlines=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};goog.string.canonicalizeNewlines=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
goog.string.normalizeWhitespace=function(a){return a.replace(/\xa0|\s/g," ")};goog.string.normalizeSpaces=function(a){return a.replace(/\xa0|[ \t]+/g," ")};goog.string.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};goog.string.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};goog.string.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};goog.string.caseInsensitiveCompare=function(a,b){var c=String(a).toLowerCase(),d=String(b).toLowerCase();return c<d?-1:c==d?0:1};
goog.string.numerateCompareRegExp_=/(\.\d+)|(\d+)|(\D+)/g;goog.string.numerateCompare=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(goog.string.numerateCompareRegExp_),d=b.toLowerCase().match(goog.string.numerateCompareRegExp_),e=Math.min(c.length,d.length),f=0;f<e;f++){var g=c[f],h=d[f];if(g!=h){c=parseInt(g,10);if(!isNaN(c)){d=parseInt(h,10);if(!isNaN(d)&&c-d)return c-d}return g<h?-1:1}}if(c.length!=d.length)return c.length-d.length;return a<b?-1:1};
goog.string.encodeUriRegExp_=/^[a-zA-Z0-9\-_.!~*'()]*$/;goog.string.urlEncode=function(a){a=String(a);if(!goog.string.encodeUriRegExp_.test(a))return encodeURIComponent(a);return a};goog.string.urlDecode=function(a){return decodeURIComponent(a.replace(/\+/g," "))};goog.string.newLineToBr=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};
goog.string.htmlEscape=function(a,b){if(b)return a.replace(goog.string.amperRe_,"&amp;").replace(goog.string.ltRe_,"&lt;").replace(goog.string.gtRe_,"&gt;").replace(goog.string.quotRe_,"&quot;");else{if(!goog.string.allRe_.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(goog.string.amperRe_,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(goog.string.ltRe_,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(goog.string.gtRe_,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(goog.string.quotRe_,"&quot;");return a}};
goog.string.amperRe_=/&/g;goog.string.ltRe_=/</g;goog.string.gtRe_=/>/g;goog.string.quotRe_=/\"/g;goog.string.allRe_=/[&<>\"]/;goog.string.unescapeEntities=function(a){if(goog.string.contains(a,"&"))return"document"in goog.global&&!goog.string.contains(a,"<")?goog.string.unescapeEntitiesUsingDom_(a):goog.string.unescapePureXmlEntities_(a);return a};
goog.string.unescapeEntitiesUsingDom_=function(a){var b=goog.global.document.createElement("div");b.innerHTML="<pre>x"+a+"</pre>";b.firstChild[goog.string.NORMALIZE_FN_]&&b.firstChild[goog.string.NORMALIZE_FN_]();a=b.firstChild.firstChild.nodeValue.slice(1);b.innerHTML="";return goog.string.canonicalizeNewlines(a)};
goog.string.unescapePureXmlEntities_=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})};goog.string.NORMALIZE_FN_="normalize";goog.string.whitespaceEscape=function(a,b){return goog.string.newLineToBr(a.replace(/  /g," &#160;"),b)};
goog.string.stripQuotes=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};goog.string.truncate=function(a,b,c){if(c)a=goog.string.unescapeEntities(a);if(a.length>b)a=a.substring(0,b-3)+"...";if(c)a=goog.string.htmlEscape(a);return a};
goog.string.truncateMiddle=function(a,b,c){if(c)a=goog.string.unescapeEntities(a);if(a.length>b){var d=Math.floor(b/2),e=a.length-d;d+=b%2;a=a.substring(0,d)+"..."+a.substring(e)}if(c)a=goog.string.htmlEscape(a);return a};goog.string.specialEscapeChars_={"\u0000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"};goog.string.jsEscapeCache_={"'":"\\'"};
goog.string.quote=function(a){a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0);b[c+1]=goog.string.specialEscapeChars_[d]||(e>31&&e<127?d:goog.string.escapeChar(d))}b.push('"');return b.join("")}};goog.string.escapeString=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=goog.string.escapeChar(a.charAt(c));return b.join("")};
goog.string.escapeChar=function(a){if(a in goog.string.jsEscapeCache_)return goog.string.jsEscapeCache_[a];if(a in goog.string.specialEscapeChars_)return goog.string.jsEscapeCache_[a]=goog.string.specialEscapeChars_[a];var b=a,c=a.charCodeAt(0);if(c>31&&c<127)b=a;else{if(c<256){b="\\x";if(c<16||c>256)b+="0"}else{b="\\u";if(c<4096)b+="0"}b+=c.toString(16).toUpperCase()}return goog.string.jsEscapeCache_[a]=b};goog.string.toMap=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=true;return b};
goog.string.contains=function(a,b){return a.indexOf(b)!=-1};goog.string.removeAt=function(a,b,c){var d=a;if(b>=0&&b<a.length&&c>0)d=a.substr(0,b)+a.substr(b+c,a.length-b-c);return d};goog.string.remove=function(a,b){var c=RegExp(goog.string.regExpEscape(b),"");return a.replace(c,"")};goog.string.removeAll=function(a,b){var c=RegExp(goog.string.regExpEscape(b),"g");return a.replace(c,"")};
goog.string.regExpEscape=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};goog.string.repeat=function(a,b){return Array(b+1).join(a)};goog.string.padNumber=function(a,b,c){a=goog.isDef(c)?a.toFixed(c):String(a);c=a.indexOf(".");if(c==-1)c=a.length;return goog.string.repeat("0",Math.max(0,b-c))+a};goog.string.makeSafe=function(a){return a==null?"":String(a)};goog.string.buildString=function(){return Array.prototype.join.call(arguments,"")};
goog.string.getRandomString=function(){return Math.floor(Math.random()*2147483648).toString(36)+(Math.floor(Math.random()*2147483648)^goog.now()).toString(36)};
goog.string.compareVersions=function(a,b){for(var c=0,d=goog.string.trim(String(a)).split("."),e=goog.string.trim(String(b)).split("."),f=Math.max(d.length,e.length),g=0;c==0&&g<f;g++){var h=d[g]||"",i=e[g]||"",j=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var m=j.exec(h)||["","",""],l=k.exec(i)||["","",""];if(m[0].length==0&&l[0].length==0)break;c=m[1].length==0?0:parseInt(m[1],10);var n=l[1].length==0?0:parseInt(l[1],10);c=goog.string.compareElements_(c,n)||goog.string.compareElements_(m[2].length==
0,l[2].length==0)||goog.string.compareElements_(m[2],l[2])}while(c==0)}return c};goog.string.compareElements_=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};goog.string.HASHCODE_MAX_=4294967296;goog.string.hashCode=function(a){for(var b=0,c=0;c<a.length;++c){b=31*b+a.charCodeAt(c);b%=goog.string.HASHCODE_MAX_}return b};goog.string.uniqueStringCounter_=Math.random()*2147483648|0;goog.string.createUniqueString=function(){return"goog_"+goog.string.uniqueStringCounter_++};
goog.string.toNumber=function(a){var b=Number(a);if(b==0&&goog.string.isEmpty(a))return NaN;return b};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){b.unshift(a);goog.debug.Error.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.doAssertFailure_=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else if(a){e+=": "+a;f=b}throw new goog.asserts.AssertionError(""+e,f||[]);};
goog.asserts.assert=function(a,b){goog.asserts.ENABLE_ASSERTS&&!a&&goog.asserts.doAssertFailure_("",null,b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.fail=function(a){if(goog.asserts.ENABLE_ASSERTS)throw new goog.asserts.AssertionError("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};
goog.asserts.assertNumber=function(a,b){goog.asserts.ENABLE_ASSERTS&&!goog.isNumber(a)&&goog.asserts.doAssertFailure_("Expected number but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertString=function(a,b){goog.asserts.ENABLE_ASSERTS&&!goog.isString(a)&&goog.asserts.doAssertFailure_("Expected string but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertFunction=function(a,b){goog.asserts.ENABLE_ASSERTS&&!goog.isFunction(a)&&goog.asserts.doAssertFailure_("Expected function but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertObject=function(a,b){goog.asserts.ENABLE_ASSERTS&&!goog.isObject(a)&&goog.asserts.doAssertFailure_("Expected object but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertArray=function(a,b){goog.asserts.ENABLE_ASSERTS&&!goog.isArray(a)&&goog.asserts.doAssertFailure_("Expected array but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertBoolean=function(a,b){goog.asserts.ENABLE_ASSERTS&&!goog.isBoolean(a)&&goog.asserts.doAssertFailure_("Expected boolean but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertInstanceof=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!(a instanceof b)&&goog.asserts.doAssertFailure_("instanceof check failed.",null,c,Array.prototype.slice.call(arguments,3))};goog.array={};goog.array.peek=function(a){return a[a.length-1]};goog.array.ARRAY_PROTOTYPE_=Array.prototype;goog.array.indexOf=goog.array.ARRAY_PROTOTYPE_.indexOf?function(a,b,c){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(goog.isString(a)){if(!goog.isString(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
goog.array.lastIndexOf=goog.array.ARRAY_PROTOTYPE_.lastIndexOf?function(a,b,c){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.lastIndexOf.call(a,b,c==null?a.length-1:c)}:function(a,b,c){c=c==null?a.length-1:c;if(c<0)c=Math.max(0,a.length+c);if(goog.isString(a)){if(!goog.isString(b)||b.length!=1)return-1;return a.lastIndexOf(b,c)}for(c=c;c>=0;c--)if(c in a&&a[c]===b)return c;return-1};
goog.array.forEach=goog.array.ARRAY_PROTOTYPE_.forEach?function(a,b,c){goog.asserts.assert(a.length!=null);goog.array.ARRAY_PROTOTYPE_.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};goog.array.forEachRight=function(a,b,c){var d=a.length,e=goog.isString(a)?a.split(""):a;for(d=d-1;d>=0;--d)d in e&&b.call(c,e[d],d,a)};
goog.array.filter=goog.array.ARRAY_PROTOTYPE_.filter?function(a,b,c){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=goog.isString(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var i=g[h];if(b.call(c,i,h,a))e[f++]=i}return e};
goog.array.map=goog.array.ARRAY_PROTOTYPE_.map?function(a,b,c){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=goog.isString(a)?a.split(""):a,g=0;g<d;g++)if(g in f)e[g]=b.call(c,f[g],g,a);return e};goog.array.reduce=function(a,b,c,d){if(a.reduce)return d?a.reduce(goog.bind(b,d),c):a.reduce(b,c);var e=c;goog.array.forEach(a,function(f,g){e=b.call(d,e,f,g,a)});return e};
goog.array.reduceRight=function(a,b,c,d){if(a.reduceRight)return d?a.reduceRight(goog.bind(b,d),c):a.reduceRight(b,c);var e=c;goog.array.forEachRight(a,function(f,g){e=b.call(d,e,f,g,a)});return e};goog.array.some=goog.array.ARRAY_PROTOTYPE_.some?function(a,b,c){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return true;return false};
goog.array.every=goog.array.ARRAY_PROTOTYPE_.every?function(a,b,c){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return false;return true};goog.array.find=function(a,b,c){b=goog.array.findIndex(a,b,c);return b<0?null:goog.isString(a)?a.charAt(b):a[b]};
goog.array.findIndex=function(a,b,c){for(var d=a.length,e=goog.isString(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};goog.array.findRight=function(a,b,c){b=goog.array.findIndexRight(a,b,c);return b<0?null:goog.isString(a)?a.charAt(b):a[b]};goog.array.findIndexRight=function(a,b,c){var d=a.length,e=goog.isString(a)?a.split(""):a;for(d=d-1;d>=0;d--)if(d in e&&b.call(c,e[d],d,a))return d;return-1};goog.array.contains=function(a,b){return goog.array.indexOf(a,b)>=0};
goog.array.isEmpty=function(a){return a.length==0};goog.array.clear=function(a){if(!goog.isArray(a))for(var b=a.length-1;b>=0;b--)delete a[b];a.length=0};goog.array.insert=function(a,b){goog.array.contains(a,b)||a.push(b)};goog.array.insertAt=function(a,b,c){goog.array.splice(a,c,0,b)};goog.array.insertArrayAt=function(a,b,c){goog.partial(goog.array.splice,a,c,0).apply(null,b)};
goog.array.insertBefore=function(a,b,c){var d;arguments.length==2||(d=goog.array.indexOf(a,c))<0?a.push(b):goog.array.insertAt(a,b,d)};goog.array.remove=function(a,b){var c=goog.array.indexOf(a,b),d;if(d=c>=0)goog.array.removeAt(a,c);return d};goog.array.removeAt=function(a,b){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.splice.call(a,b,1).length==1};goog.array.removeIf=function(a,b,c){b=goog.array.findIndex(a,b,c);if(b>=0){goog.array.removeAt(a,b);return true}return false};
goog.array.concat=function(){return goog.array.ARRAY_PROTOTYPE_.concat.apply(goog.array.ARRAY_PROTOTYPE_,arguments)};goog.array.clone=function(a){if(goog.isArray(a))return goog.array.concat(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};goog.array.toArray=function(a){if(goog.isArray(a))return goog.array.concat(a);return goog.array.clone(a)};
goog.array.extend=function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;if(goog.isArray(c)||(d=goog.isArrayLike(c))&&c.hasOwnProperty("callee"))a.push.apply(a,c);else if(d)for(var e=a.length,f=c.length,g=0;g<f;g++)a[e+g]=c[g];else a.push(c)}};goog.array.splice=function(a){goog.asserts.assert(a.length!=null);return goog.array.ARRAY_PROTOTYPE_.splice.apply(a,goog.array.slice(arguments,1))};
goog.array.slice=function(a,b,c){goog.asserts.assert(a.length!=null);return arguments.length<=2?goog.array.ARRAY_PROTOTYPE_.slice.call(a,b):goog.array.ARRAY_PROTOTYPE_.slice.call(a,b,c)};goog.array.removeDuplicates=function(a,b){for(var c=b||a,d={},e=0,f=0;f<a.length;){var g=a[f++],h=goog.isObject(g)?goog.getUid(g):g;if(!Object.prototype.hasOwnProperty.call(d,h)){d[h]=true;c[e++]=g}}c.length=e};
goog.array.binarySearch=function(a,b,c){return goog.array.binarySearch_(a,c||goog.array.defaultCompare,false,b)};goog.array.binarySelect=function(a,b,c){return goog.array.binarySearch_(a,b,true,undefined,c)};goog.array.binarySearch_=function(a,b,c,d,e){for(var f=0,g=a.length,h;f<g;){var i=f+g>>1,j;j=c?b.call(e,a[i],i,a):b(d,a[i]);if(j>0)f=i+1;else{g=i;h=!j}}return h?f:~f};goog.array.sort=function(a,b){goog.asserts.assert(a.length!=null);goog.array.ARRAY_PROTOTYPE_.sort.call(a,b||goog.array.defaultCompare)};
goog.array.stableSort=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||goog.array.defaultCompare;goog.array.sort(a,function(e,f){return d(e.value,f.value)||e.index-f.index});for(c=0;c<a.length;c++)a[c]=a[c].value};goog.array.sortObjectsByKey=function(a,b,c){var d=c||goog.array.defaultCompare;goog.array.sort(a,function(e,f){return d(e[b],f[b])})};
goog.array.equals=function(a,b,c){if(!goog.isArrayLike(a)||!goog.isArrayLike(b)||a.length!=b.length)return false;var d=a.length;c=c||goog.array.defaultCompareEquality;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return false;return true};goog.array.compare=function(a,b,c){return goog.array.equals(a,b,c)};goog.array.defaultCompare=function(a,b){return a>b?1:a<b?-1:0};goog.array.defaultCompareEquality=function(a,b){return a===b};
goog.array.binaryInsert=function(a,b,c){c=goog.array.binarySearch(a,b,c);if(c<0){goog.array.insertAt(a,b,-(c+1));return true}return false};goog.array.binaryRemove=function(a,b,c){b=goog.array.binarySearch(a,b,c);return b>=0?goog.array.removeAt(a,b):false};goog.array.bucket=function(a,b){for(var c={},d=0;d<a.length;d++){var e=a[d],f=b(e,d,a);if(goog.isDef(f))(c[f]||(c[f]=[])).push(e)}return c};goog.array.repeat=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c};
goog.array.flatten=function(){for(var a=[],b=0;b<arguments.length;b++){var c=arguments[b];goog.isArray(c)?a.push.apply(a,goog.array.flatten.apply(null,c)):a.push(c)}return a};goog.array.rotate=function(a,b){goog.asserts.assert(a.length!=null);if(a.length){b%=a.length;if(b>0)goog.array.ARRAY_PROTOTYPE_.unshift.apply(a,a.splice(-b,b));else b<0&&goog.array.ARRAY_PROTOTYPE_.push.apply(a,a.splice(0,-b))}return a};
goog.array.zip=function(){if(!arguments.length)return[];for(var a=[],b=0;;b++){for(var c=[],d=0;d<arguments.length;d++){var e=arguments[d];if(b>=e.length)return a;c.push(e[b])}a.push(c)}};goog.debug.entryPointRegistry={};goog.debug.EntryPointMonitor=function(){};goog.debug.entryPointRegistry.refList_=[];goog.debug.entryPointRegistry.register=function(a){goog.debug.entryPointRegistry.refList_[goog.debug.entryPointRegistry.refList_.length]=a};goog.debug.entryPointRegistry.monitorAll=function(a){a=goog.bind(a.wrap,a);for(var b=0;b<goog.debug.entryPointRegistry.refList_.length;b++)goog.debug.entryPointRegistry.refList_[b](a)};
goog.debug.entryPointRegistry.unmonitorAllIfPossible=function(a){a=goog.bind(a.unwrap,a);for(var b=0;b<goog.debug.entryPointRegistry.refList_.length;b++)goog.debug.entryPointRegistry.refList_[b](a)};goog.debug.errorHandlerWeakDep={protectEntryPoint:function(a){return a}};goog.userAgent={};goog.userAgent.ASSUME_IE=false;goog.userAgent.ASSUME_GECKO=false;goog.userAgent.ASSUME_WEBKIT=false;goog.userAgent.ASSUME_MOBILE_WEBKIT=false;goog.userAgent.ASSUME_OPERA=false;goog.userAgent.BROWSER_KNOWN_=goog.userAgent.ASSUME_IE||goog.userAgent.ASSUME_GECKO||goog.userAgent.ASSUME_MOBILE_WEBKIT||goog.userAgent.ASSUME_WEBKIT||goog.userAgent.ASSUME_OPERA;goog.userAgent.getUserAgentString=function(){return goog.global.navigator?goog.global.navigator.userAgent:null};
goog.userAgent.getNavigator=function(){return goog.global.navigator};
goog.userAgent.init_=function(){goog.userAgent.detectedOpera_=false;goog.userAgent.detectedIe_=false;goog.userAgent.detectedWebkit_=false;goog.userAgent.detectedMobile_=false;goog.userAgent.detectedGecko_=false;var a;if(!goog.userAgent.BROWSER_KNOWN_&&(a=goog.userAgent.getUserAgentString())){var b=goog.userAgent.getNavigator();goog.userAgent.detectedOpera_=a.indexOf("Opera")==0;goog.userAgent.detectedIe_=!goog.userAgent.detectedOpera_&&a.indexOf("MSIE")!=-1;goog.userAgent.detectedWebkit_=!goog.userAgent.detectedOpera_&&
a.indexOf("WebKit")!=-1;goog.userAgent.detectedMobile_=goog.userAgent.detectedWebkit_&&a.indexOf("Mobile")!=-1;goog.userAgent.detectedGecko_=!goog.userAgent.detectedOpera_&&!goog.userAgent.detectedWebkit_&&b.product=="Gecko"}};goog.userAgent.BROWSER_KNOWN_||goog.userAgent.init_();goog.userAgent.OPERA=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_OPERA:goog.userAgent.detectedOpera_;goog.userAgent.IE=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_IE:goog.userAgent.detectedIe_;
goog.userAgent.GECKO=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_GECKO:goog.userAgent.detectedGecko_;goog.userAgent.WEBKIT=goog.userAgent.BROWSER_KNOWN_?goog.userAgent.ASSUME_WEBKIT||goog.userAgent.ASSUME_MOBILE_WEBKIT:goog.userAgent.detectedWebkit_;goog.userAgent.MOBILE=goog.userAgent.ASSUME_MOBILE_WEBKIT||goog.userAgent.detectedMobile_;goog.userAgent.SAFARI=goog.userAgent.WEBKIT;goog.userAgent.determinePlatform_=function(){var a=goog.userAgent.getNavigator();return a&&a.platform||""};
goog.userAgent.PLATFORM=goog.userAgent.determinePlatform_();goog.userAgent.ASSUME_MAC=false;goog.userAgent.ASSUME_WINDOWS=false;goog.userAgent.ASSUME_LINUX=false;goog.userAgent.ASSUME_X11=false;goog.userAgent.PLATFORM_KNOWN_=goog.userAgent.ASSUME_MAC||goog.userAgent.ASSUME_WINDOWS||goog.userAgent.ASSUME_LINUX||goog.userAgent.ASSUME_X11;
goog.userAgent.initPlatform_=function(){goog.userAgent.detectedMac_=goog.string.contains(goog.userAgent.PLATFORM,"Mac");goog.userAgent.detectedWindows_=goog.string.contains(goog.userAgent.PLATFORM,"Win");goog.userAgent.detectedLinux_=goog.string.contains(goog.userAgent.PLATFORM,"Linux");goog.userAgent.detectedX11_=!!goog.userAgent.getNavigator()&&goog.string.contains(goog.userAgent.getNavigator().appVersion||"","X11")};goog.userAgent.PLATFORM_KNOWN_||goog.userAgent.initPlatform_();
goog.userAgent.MAC=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_MAC:goog.userAgent.detectedMac_;goog.userAgent.WINDOWS=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_WINDOWS:goog.userAgent.detectedWindows_;goog.userAgent.LINUX=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_LINUX:goog.userAgent.detectedLinux_;goog.userAgent.X11=goog.userAgent.PLATFORM_KNOWN_?goog.userAgent.ASSUME_X11:goog.userAgent.detectedX11_;
goog.userAgent.determineVersion_=function(){var a="",b;if(goog.userAgent.OPERA&&goog.global.opera){a=goog.global.opera.version;a=typeof a=="function"?a():a}else{if(goog.userAgent.GECKO)b=/rv\:([^\);]+)(\)|;)/;else if(goog.userAgent.IE)b=/MSIE\s+([^\);]+)(\)|;)/;else if(goog.userAgent.WEBKIT)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(goog.userAgent.getUserAgentString()))?a[1]:""}if(goog.userAgent.IE){b=goog.userAgent.getDocumentMode_();if(b>parseFloat(a))return String(b)}return a};
goog.userAgent.getDocumentMode_=function(){var a=goog.global.document;return a?a.documentMode:undefined};goog.userAgent.VERSION=goog.userAgent.determineVersion_();goog.userAgent.compare=function(a,b){return goog.string.compareVersions(a,b)};goog.userAgent.isVersionCache_={};goog.userAgent.isVersion=function(a){return goog.userAgent.isVersionCache_[a]||(goog.userAgent.isVersionCache_[a]=goog.string.compareVersions(goog.userAgent.VERSION,a)>=0)};goog.events={};goog.events.BrowserFeature={HAS_W3C_BUTTON:!goog.userAgent.IE||goog.userAgent.isVersion("9"),SET_KEY_CODE_TO_PREVENT_DEFAULT:goog.userAgent.IE&&!goog.userAgent.isVersion("8")};goog.events.Event=function(a,b){goog.Disposable.call(this);this.type=a;this.currentTarget=this.target=b};goog.inherits(goog.events.Event,goog.Disposable);goog.events.Event.prototype.disposeInternal=function(){delete this.type;delete this.target;delete this.currentTarget};goog.events.Event.prototype.propagationStopped_=false;goog.events.Event.prototype.returnValue_=true;goog.events.Event.prototype.stopPropagation=function(){this.propagationStopped_=true};
goog.events.Event.prototype.preventDefault=function(){this.returnValue_=false};goog.events.Event.stopPropagation=function(a){a.stopPropagation()};goog.events.Event.preventDefault=function(a){a.preventDefault()};goog.events.EventType={CLICK:"click",DBLCLICK:"dblclick",MOUSEDOWN:"mousedown",MOUSEUP:"mouseup",MOUSEOVER:"mouseover",MOUSEOUT:"mouseout",MOUSEMOVE:"mousemove",SELECTSTART:"selectstart",KEYPRESS:"keypress",KEYDOWN:"keydown",KEYUP:"keyup",BLUR:"blur",FOCUS:"focus",DEACTIVATE:"deactivate",FOCUSIN:goog.userAgent.IE?"focusin":"DOMFocusIn",FOCUSOUT:goog.userAgent.IE?"focusout":"DOMFocusOut",CHANGE:"change",SELECT:"select",SUBMIT:"submit",INPUT:"input",PROPERTYCHANGE:"propertychange",DRAGSTART:"dragstart",
DRAGENTER:"dragenter",DRAGOVER:"dragover",DRAGLEAVE:"dragleave",DROP:"drop",TOUCHSTART:"touchstart",TOUCHMOVE:"touchmove",TOUCHEND:"touchend",TOUCHCANCEL:"touchcancel",CONTEXTMENU:"contextmenu",ERROR:"error",HELP:"help",LOAD:"load",LOSECAPTURE:"losecapture",READYSTATECHANGE:"readystatechange",RESIZE:"resize",SCROLL:"scroll",UNLOAD:"unload",HASHCHANGE:"hashchange",POPSTATE:"popstate"};goog.events.BrowserEvent=function(a,b){a&&this.init(a,b)};goog.inherits(goog.events.BrowserEvent,goog.events.Event);goog.events.BrowserEvent.MouseButton={LEFT:0,MIDDLE:1,RIGHT:2};goog.events.BrowserEvent.IEButtonMap_=[1,4,2];goog.events.BrowserEvent.prototype.target=null;goog.events.BrowserEvent.prototype.relatedTarget=null;goog.events.BrowserEvent.prototype.offsetX=0;goog.events.BrowserEvent.prototype.offsetY=0;goog.events.BrowserEvent.prototype.clientX=0;
goog.events.BrowserEvent.prototype.clientY=0;goog.events.BrowserEvent.prototype.screenX=0;goog.events.BrowserEvent.prototype.screenY=0;goog.events.BrowserEvent.prototype.button=0;goog.events.BrowserEvent.prototype.keyCode=0;goog.events.BrowserEvent.prototype.charCode=0;goog.events.BrowserEvent.prototype.ctrlKey=false;goog.events.BrowserEvent.prototype.altKey=false;goog.events.BrowserEvent.prototype.shiftKey=false;goog.events.BrowserEvent.prototype.metaKey=false;
goog.events.BrowserEvent.prototype.platformModifierKey=false;goog.events.BrowserEvent.prototype.event_=null;
goog.events.BrowserEvent.prototype.init=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(goog.userAgent.GECKO)try{d=d.nodeName&&d}catch(e){d=null}}else if(c==goog.events.EventType.MOUSEOVER)d=a.fromElement;else if(c==goog.events.EventType.MOUSEOUT)d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?
a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.platformModifierKey=goog.userAgent.MAC?a.metaKey:a.ctrlKey;this.event_=a;delete this.returnValue_;delete this.propagationStopped_};
goog.events.BrowserEvent.prototype.isButton=function(a){return goog.events.BrowserFeature.HAS_W3C_BUTTON?this.event_.button==a:this.type=="click"?a==goog.events.BrowserEvent.MouseButton.LEFT:!!(this.event_.button&goog.events.BrowserEvent.IEButtonMap_[a])};goog.events.BrowserEvent.prototype.stopPropagation=function(){goog.events.BrowserEvent.superClass_.stopPropagation.call(this);if(this.event_.stopPropagation)this.event_.stopPropagation();else this.event_.cancelBubble=true};
goog.events.BrowserEvent.prototype.preventDefault=function(){goog.events.BrowserEvent.superClass_.preventDefault.call(this);var a=this.event_;if(a.preventDefault)a.preventDefault();else{a.returnValue=false;if(goog.events.BrowserFeature.SET_KEY_CODE_TO_PREVENT_DEFAULT)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};goog.events.BrowserEvent.prototype.getBrowserEvent=function(){return this.event_};
goog.events.BrowserEvent.prototype.disposeInternal=function(){goog.events.BrowserEvent.superClass_.disposeInternal.call(this);this.relatedTarget=this.currentTarget=this.target=this.event_=null};goog.events.EventWrapper=function(){};goog.events.EventWrapper.prototype.listen=function(){};goog.events.EventWrapper.prototype.unlisten=function(){};goog.events.Listener=function(){};goog.events.Listener.counter_=0;goog.events.Listener.prototype.key=0;goog.events.Listener.prototype.removed=false;goog.events.Listener.prototype.callOnce=false;
goog.events.Listener.prototype.init=function(a,b,c,d,e,f){if(goog.isFunction(a))this.isFunctionListener_=true;else if(a&&a.handleEvent&&goog.isFunction(a.handleEvent))this.isFunctionListener_=false;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.callOnce=false;this.key=++goog.events.Listener.counter_;this.removed=false};
goog.events.Listener.prototype.handleEvent=function(a){if(this.isFunctionListener_)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};goog.structs={};goog.structs.SimplePool=function(a,b){goog.Disposable.call(this);this.maxCount_=b;this.freeQueue_=[];this.createInitial_(a)};goog.inherits(goog.structs.SimplePool,goog.Disposable);goog.structs.SimplePool.prototype.createObjectFn_=null;goog.structs.SimplePool.prototype.disposeObjectFn_=null;goog.structs.SimplePool.prototype.setCreateObjectFn=function(a){this.createObjectFn_=a};goog.structs.SimplePool.prototype.setDisposeObjectFn=function(a){this.disposeObjectFn_=a};
goog.structs.SimplePool.prototype.getObject=function(){if(this.freeQueue_.length)return this.freeQueue_.pop();return this.createObject()};goog.structs.SimplePool.prototype.releaseObject=function(a){this.freeQueue_.length<this.maxCount_?this.freeQueue_.push(a):this.disposeObject(a)};goog.structs.SimplePool.prototype.createInitial_=function(a){if(a>this.maxCount_)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.freeQueue_.push(this.createObject())};
goog.structs.SimplePool.prototype.createObject=function(){return this.createObjectFn_?this.createObjectFn_():{}};goog.structs.SimplePool.prototype.disposeObject=function(a){if(this.disposeObjectFn_)this.disposeObjectFn_(a);else if(goog.isObject(a))if(goog.isFunction(a.dispose))a.dispose();else for(var b in a)delete a[b]};
goog.structs.SimplePool.prototype.disposeInternal=function(){goog.structs.SimplePool.superClass_.disposeInternal.call(this);for(var a=this.freeQueue_;a.length;)this.disposeObject(a.pop());delete this.freeQueue_};goog.userAgent.jscript={};goog.userAgent.jscript.ASSUME_NO_JSCRIPT=false;goog.userAgent.jscript.init_=function(){goog.userAgent.jscript.DETECTED_HAS_JSCRIPT_="ScriptEngine"in goog.global&&goog.global.ScriptEngine()=="JScript";goog.userAgent.jscript.DETECTED_VERSION_=goog.userAgent.jscript.DETECTED_HAS_JSCRIPT_?goog.global.ScriptEngineMajorVersion()+"."+goog.global.ScriptEngineMinorVersion()+"."+goog.global.ScriptEngineBuildVersion():"0"};goog.userAgent.jscript.ASSUME_NO_JSCRIPT||goog.userAgent.jscript.init_();
goog.userAgent.jscript.HAS_JSCRIPT=goog.userAgent.jscript.ASSUME_NO_JSCRIPT?false:goog.userAgent.jscript.DETECTED_HAS_JSCRIPT_;goog.userAgent.jscript.VERSION=goog.userAgent.jscript.ASSUME_NO_JSCRIPT?"0":goog.userAgent.jscript.DETECTED_VERSION_;goog.userAgent.jscript.isVersion=function(a){return goog.string.compareVersions(goog.userAgent.jscript.VERSION,a)>=0};goog.events.pools={};
(function(){function a(){return{count_:0,remaining_:0}}function b(){return[]}function c(){var l=function(n){return g.call(l.src,l.key,n)};return l}function d(){return new goog.events.Listener}function e(){return new goog.events.BrowserEvent}var f=goog.userAgent.jscript.HAS_JSCRIPT&&!goog.userAgent.jscript.isVersion("5.7"),g;goog.events.pools.setProxyCallbackFunction=function(l){g=l};if(f){goog.events.pools.getObject=function(){return h.getObject()};goog.events.pools.releaseObject=function(l){h.releaseObject(l)};
goog.events.pools.getArray=function(){return i.getObject()};goog.events.pools.releaseArray=function(l){i.releaseObject(l)};goog.events.pools.getProxy=function(){return j.getObject()};goog.events.pools.releaseProxy=function(){j.releaseObject(c())};goog.events.pools.getListener=function(){return k.getObject()};goog.events.pools.releaseListener=function(l){k.releaseObject(l)};goog.events.pools.getEvent=function(){return m.getObject()};goog.events.pools.releaseEvent=function(l){m.releaseObject(l)};var h=
new goog.structs.SimplePool(0,600);h.setCreateObjectFn(a);var i=new goog.structs.SimplePool(0,600);i.setCreateObjectFn(b);var j=new goog.structs.SimplePool(0,600);j.setCreateObjectFn(c);var k=new goog.structs.SimplePool(0,600);k.setCreateObjectFn(d);var m=new goog.structs.SimplePool(0,600);m.setCreateObjectFn(e)}else{goog.events.pools.getObject=a;goog.events.pools.releaseObject=goog.nullFunction;goog.events.pools.getArray=b;goog.events.pools.releaseArray=goog.nullFunction;goog.events.pools.getProxy=
c;goog.events.pools.releaseProxy=goog.nullFunction;goog.events.pools.getListener=d;goog.events.pools.releaseListener=goog.nullFunction;goog.events.pools.getEvent=e;goog.events.pools.releaseEvent=goog.nullFunction}})();goog.object={};goog.object.forEach=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};goog.object.filter=function(a,b,c){var d={},e;for(e in a)if(b.call(c,a[e],e,a))d[e]=a[e];return d};goog.object.map=function(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d};goog.object.some=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return true;return false};goog.object.every=function(a,b,c){for(var d in a)if(!b.call(c,a[d],d,a))return false;return true};
goog.object.getCount=function(a){var b=0,c;for(c in a)b++;return b};goog.object.getAnyKey=function(a){for(var b in a)return b};goog.object.getAnyValue=function(a){for(var b in a)return a[b]};goog.object.contains=function(a,b){return goog.object.containsValue(a,b)};goog.object.getValues=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};goog.object.getKeys=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};goog.object.containsKey=function(a,b){return b in a};
goog.object.containsValue=function(a,b){for(var c in a)if(a[c]==b)return true;return false};goog.object.findKey=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};goog.object.findValue=function(a,b,c){return(b=goog.object.findKey(a,b,c))&&a[b]};goog.object.isEmpty=function(a){for(var b in a)return false;return true};goog.object.clear=function(a){for(var b=goog.object.getKeys(a),c=b.length-1;c>=0;c--)goog.object.remove(a,b[c])};
goog.object.remove=function(a,b){var c;if(c=b in a)delete a[b];return c};goog.object.add=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');goog.object.set(a,b,c)};goog.object.get=function(a,b,c){if(b in a)return a[b];return c};goog.object.set=function(a,b,c){a[b]=c};goog.object.setIfUndefined=function(a,b,c){return b in a?a[b]:a[b]=c};goog.object.clone=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
goog.object.transpose=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};goog.object.PROTOTYPE_FIELDS_=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];goog.object.extend=function(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<goog.object.PROTOTYPE_FIELDS_.length;e++){b=goog.object.PROTOTYPE_FIELDS_[e];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}};
goog.object.create=function(){var a=arguments.length;if(a==1&&goog.isArray(arguments[0]))return goog.object.create.apply(null,arguments[0]);if(a%2)throw Error("Uneven number of arguments");for(var b={},c=0;c<a;c+=2)b[arguments[c]]=arguments[c+1];return b};goog.object.createSet=function(){var a=arguments.length;if(a==1&&goog.isArray(arguments[0]))return goog.object.createSet.apply(null,arguments[0]);for(var b={},c=0;c<a;c++)b[arguments[c]]=true;return b};goog.events.listeners_={};goog.events.listenerTree_={};goog.events.sources_={};goog.events.onString_="on";goog.events.onStringMap_={};goog.events.keySeparator_="_";
goog.events.listen=function(a,b,c,d,e){if(b)if(goog.isArray(b)){for(var f=0;f<b.length;f++)goog.events.listen(a,b[f],c,d,e);return null}else{d=!!d;var g=goog.events.listenerTree_;b in g||(g[b]=goog.events.pools.getObject());g=g[b];if(!(d in g)){g[d]=goog.events.pools.getObject();g.count_++}g=g[d];var h=goog.getUid(a),i;g.remaining_++;if(g[h]){i=g[h];for(f=0;f<i.length;f++){g=i[f];if(g.listener==c&&g.handler==e){if(g.removed)break;return i[f].key}}}else{i=g[h]=goog.events.pools.getArray();g.count_++}f=
goog.events.pools.getProxy();f.src=a;g=goog.events.pools.getListener();g.init(c,f,a,b,d,e);c=g.key;f.key=c;i.push(g);goog.events.listeners_[c]=g;goog.events.sources_[h]||(goog.events.sources_[h]=goog.events.pools.getArray());goog.events.sources_[h].push(g);if(a.addEventListener){if(a==goog.global||!a.customEvent_)a.addEventListener(b,f,d)}else a.attachEvent(goog.events.getOnString_(b),f);return c}else throw Error("Invalid event type");};
goog.events.listenOnce=function(a,b,c,d,e){if(goog.isArray(b)){for(var f=0;f<b.length;f++)goog.events.listenOnce(a,b[f],c,d,e);return null}a=goog.events.listen(a,b,c,d,e);goog.events.listeners_[a].callOnce=true;return a};goog.events.listenWithWrapper=function(a,b,c,d,e){b.listen(a,c,d,e)};
goog.events.unlisten=function(a,b,c,d,e){if(goog.isArray(b)){for(var f=0;f<b.length;f++)goog.events.unlisten(a,b[f],c,d,e);return null}d=!!d;a=goog.events.getListeners_(a,b,d);if(!a)return false;for(f=0;f<a.length;f++)if(a[f].listener==c&&a[f].capture==d&&a[f].handler==e)return goog.events.unlistenByKey(a[f].key);return false};
goog.events.unlistenByKey=function(a){if(!goog.events.listeners_[a])return false;var b=goog.events.listeners_[a];if(b.removed)return false;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==goog.global||!c.customEvent_)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(goog.events.getOnString_(d),e);c=goog.getUid(c);e=goog.events.listenerTree_[d][f][c];if(goog.events.sources_[c]){var g=goog.events.sources_[c];goog.array.remove(g,b);g.length==0&&delete goog.events.sources_[c]}b.removed=
true;e.needsCleanup_=true;goog.events.cleanUp_(d,f,c,e);delete goog.events.listeners_[a];return true};goog.events.unlistenWithWrapper=function(a,b,c,d,e){b.unlisten(a,c,d,e)};
goog.events.cleanUp_=function(a,b,c,d){if(!d.locked_)if(d.needsCleanup_){for(var e=0,f=0;e<d.length;e++)if(d[e].removed){var g=d[e].proxy;g.src=null;goog.events.pools.releaseProxy(g);goog.events.pools.releaseListener(d[e])}else{if(e!=f)d[f]=d[e];f++}d.length=f;d.needsCleanup_=false;if(f==0){goog.events.pools.releaseArray(d);delete goog.events.listenerTree_[a][b][c];goog.events.listenerTree_[a][b].count_--;if(goog.events.listenerTree_[a][b].count_==0){goog.events.pools.releaseObject(goog.events.listenerTree_[a][b]);
delete goog.events.listenerTree_[a][b];goog.events.listenerTree_[a].count_--}if(goog.events.listenerTree_[a].count_==0){goog.events.pools.releaseObject(goog.events.listenerTree_[a]);delete goog.events.listenerTree_[a]}}}};
goog.events.removeAll=function(a,b,c){var d=0,e=a==null,f=b==null,g=c==null;c=!!c;if(e)goog.object.forEach(goog.events.sources_,function(i){for(var j=i.length-1;j>=0;j--){var k=i[j];if((f||b==k.type)&&(g||c==k.capture)){goog.events.unlistenByKey(k.key);d++}}});else{a=goog.getUid(a);if(goog.events.sources_[a]){a=goog.events.sources_[a];for(e=a.length-1;e>=0;e--){var h=a[e];if((f||b==h.type)&&(g||c==h.capture)){goog.events.unlistenByKey(h.key);d++}}}}return d};
goog.events.getListeners=function(a,b,c){return goog.events.getListeners_(a,b,c)||[]};goog.events.getListeners_=function(a,b,c){var d=goog.events.listenerTree_;if(b in d){d=d[b];if(c in d){d=d[c];a=goog.getUid(a);if(d[a])return d[a]}}return null};goog.events.getListener=function(a,b,c,d,e){d=!!d;if(a=goog.events.getListeners_(a,b,d))for(b=0;b<a.length;b++)if(a[b].listener==c&&a[b].capture==d&&a[b].handler==e)return a[b];return null};
goog.events.hasListener=function(a,b,c){a=goog.getUid(a);var d=goog.events.sources_[a];if(d){var e=goog.isDef(b),f=goog.isDef(c);if(e&&f){d=goog.events.listenerTree_[b];return!!d&&!!d[c]&&a in d[c]}else return e||f?goog.array.some(d,function(g){return e&&g.type==b||f&&g.capture==c}):true}return false};goog.events.expose=function(a){var b=[],c;for(c in a)a[c]&&a[c].id?b.push(c+" = "+a[c]+" ("+a[c].id+")"):b.push(c+" = "+a[c]);return b.join("\n")};
goog.events.getOnString_=function(a){if(a in goog.events.onStringMap_)return goog.events.onStringMap_[a];return goog.events.onStringMap_[a]=goog.events.onString_+a};goog.events.fireListeners=function(a,b,c,d){var e=goog.events.listenerTree_;if(b in e){e=e[b];if(c in e)return goog.events.fireListeners_(e[c],a,b,c,d)}return true};
goog.events.fireListeners_=function(a,b,c,d,e){var f=1;b=goog.getUid(b);if(a[b]){a.remaining_--;a=a[b];if(a.locked_)a.locked_++;else a.locked_=1;try{for(var g=a.length,h=0;h<g;h++){var i=a[h];if(i&&!i.removed)f&=goog.events.fireListener(i,e)!==false}}finally{a.locked_--;goog.events.cleanUp_(c,d,b,a)}}return Boolean(f)};goog.events.fireListener=function(a,b){var c=a.handleEvent(b);a.callOnce&&goog.events.unlistenByKey(a.key);return c};goog.events.getTotalListenerCount=function(){return goog.object.getCount(goog.events.listeners_)};
goog.events.dispatchEvent=function(a,b){if(goog.isString(b))b=new goog.events.Event(b,a);else if(b instanceof goog.events.Event)b.target=b.target||a;else{var c=b;b=new goog.events.Event(b.type,a);goog.object.extend(b,c)}c=1;var d,e=b.type,f=goog.events.listenerTree_;if(!(e in f))return true;f=f[e];e=true in f;var g;if(e){d=[];for(g=a;g;g=g.getParentEventTarget())d.push(g);g=f[true];g.remaining_=g.count_;for(var h=d.length-1;!b.propagationStopped_&&h>=0&&g.remaining_;h--){b.currentTarget=d[h];c&=goog.events.fireListeners_(g,
d[h],b.type,true,b)&&b.returnValue_!=false}}if(false in f){g=f[false];g.remaining_=g.count_;if(e)for(h=0;!b.propagationStopped_&&h<d.length&&g.remaining_;h++){b.currentTarget=d[h];c&=goog.events.fireListeners_(g,d[h],b.type,false,b)&&b.returnValue_!=false}else for(d=a;!b.propagationStopped_&&d&&g.remaining_;d=d.getParentEventTarget()){b.currentTarget=d;c&=goog.events.fireListeners_(g,d,b.type,false,b)&&b.returnValue_!=false}}return Boolean(c)};
goog.events.protectBrowserEventEntryPoint=function(a){goog.events.handleBrowserEvent_=a.protectEntryPoint(goog.events.handleBrowserEvent_);goog.events.pools.setProxyCallbackFunction(goog.events.handleBrowserEvent_)};
goog.events.handleBrowserEvent_=function(a,b){if(!goog.events.listeners_[a])return true;var c=goog.events.listeners_[a],d=c.type,e=goog.events.listenerTree_;if(!(d in e))return true;e=e[d];var f,g;if(goog.events.synthesizeEventPropagation_()){f=b||goog.getObjectByName("window.event");var h=true in e,i=false in e;if(h){if(goog.events.isMarkedIeEvent_(f))return true;goog.events.markIeEvent_(f)}var j=goog.events.pools.getEvent();j.init(f,this);f=true;try{if(h){for(var k=goog.events.pools.getArray(),
m=j.currentTarget;m;m=m.parentNode)k.push(m);g=e[true];g.remaining_=g.count_;for(var l=k.length-1;!j.propagationStopped_&&l>=0&&g.remaining_;l--){j.currentTarget=k[l];f&=goog.events.fireListeners_(g,k[l],d,true,j)}if(i){g=e[false];g.remaining_=g.count_;for(l=0;!j.propagationStopped_&&l<k.length&&g.remaining_;l++){j.currentTarget=k[l];f&=goog.events.fireListeners_(g,k[l],d,false,j)}}}else f=goog.events.fireListener(c,j)}finally{if(k){k.length=0;goog.events.pools.releaseArray(k)}j.dispose();goog.events.pools.releaseEvent(j)}return f}d=
new goog.events.BrowserEvent(b,this);try{f=goog.events.fireListener(c,d)}finally{d.dispose()}return f};goog.events.pools.setProxyCallbackFunction(goog.events.handleBrowserEvent_);goog.events.markIeEvent_=function(a){var b=false;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=true}if(b||a.returnValue==undefined)a.returnValue=true};goog.events.isMarkedIeEvent_=function(a){return a.keyCode<0||a.returnValue!=undefined};goog.events.uniqueIdCounter_=0;
goog.events.getUniqueId=function(a){return a+"_"+goog.events.uniqueIdCounter_++};goog.events.synthesizeEventPropagation_=function(){if(goog.events.requiresSyntheticEventPropagation_===undefined)goog.events.requiresSyntheticEventPropagation_=goog.userAgent.IE&&!goog.global.addEventListener;return goog.events.requiresSyntheticEventPropagation_};goog.debug.entryPointRegistry.register(function(a){goog.events.handleBrowserEvent_=a(goog.events.handleBrowserEvent_);goog.events.pools.setProxyCallbackFunction(goog.events.handleBrowserEvent_)});goog.events.EventTarget=function(){goog.Disposable.call(this)};goog.inherits(goog.events.EventTarget,goog.Disposable);goog.events.EventTarget.prototype.customEvent_=true;goog.events.EventTarget.prototype.parentEventTarget_=null;goog.events.EventTarget.prototype.getParentEventTarget=function(){return this.parentEventTarget_};goog.events.EventTarget.prototype.setParentEventTarget=function(a){this.parentEventTarget_=a};
goog.events.EventTarget.prototype.addEventListener=function(a,b,c,d){goog.events.listen(this,a,b,c,d)};goog.events.EventTarget.prototype.removeEventListener=function(a,b,c,d){goog.events.unlisten(this,a,b,c,d)};goog.events.EventTarget.prototype.dispatchEvent=function(a){return goog.events.dispatchEvent(this,a)};goog.events.EventTarget.prototype.disposeInternal=function(){goog.events.EventTarget.superClass_.disposeInternal.call(this);goog.events.removeAll(this);this.parentEventTarget_=null};crow.Graph=function(){this.nodes=[];this.map={};this.version="0";this.validator=new goog.events.EventTarget;this.height=this.width=0;this.addNode=function(a){a._initialize();if(a.getX&&a.getY){var b=a.getX(),c=a.getY();if(b+1>this.width)this.width=b+1;if(c+1>this.height)this.height=c+1}this.nodes.push(a);this.map[a.id]=a};this.removeNode=function(a,b,c){if(typeof a==="number"){delete this.map[""+a+"_"+b];for(var d=0;d<this.nodes.length;d++){var e=this.nodes[d];if(e.x==a&&e.y==b){this.nodes.splice(d,
1);break}}c&&this.invalidate(a,b)}else delete this.map[a.id]};this.getNode=function(a,b,c){var d;if(typeof a==="function")for(var e=0;e<this.nodes.length;e++){var f=this.nodes[e];if(a.call(f)){d=f;break}}else if(typeof a==="string")return this.map[a];else{if(typeof a!=="number")throw Error("x coordinate not provided");if(typeof b!=="number")throw Error("y coordinate not provided");d=this.map[""+a+"_"+b]}if(d)return d;else if(c&&typeof a==="number"){d=new crow.BaseNode([a,b]);d.isBlank=true;return d}};
this.getNodes=function(a){switch(typeof a){case "function":return this.getNodes({filter:a});case "object":var b=a.start||this.nodes[0],c=crow.Graph._lookupAlgorithm(a.algorithm||"linear");if(!(c.prototype instanceof crow.algorithm.SearchAlgorithm))throw Error("only compatible with SearchAlgorithms");return(new c(this)).search(b,{filter:a.filter});case "undefined":return this.nodes;default:throw Error("unsupported object "+a.toString());}};this.findGoal=function(a){return crow.Graph.findGoal(a,this)};
this.invalidate=function(a,b,c,d){if(c==0||d==0)throw Error("dx and dy can't be 0");c&&d?this.validator.dispatchEvent({type:"invalidateRegion",x:a,y:b,dx:c,dy:d}):this.validator.dispatchEvent({type:"invalidatePoint",x:a,y:b})}};
crow.Graph.findGoal=function(a,b){crow.Algorithm.initializeDataStructures();var c=a.start||b&&b.nodes[0];if(!c)throw Error("To go somewhere you must know where you start...perhaps you meant to provide a start node?");var d=a.goal,e=crow.Graph._lookupAlgorithm(a.algorithm)||crow.AlgorithmResolver.getAlgorithm();if(!(e.prototype instanceof crow.algorithm.ShortestPathAlgorithm))throw Error("only compatible with ShortestPathAlgorithms");a.graph=b;return(new e(b)).findPath(c,d,a)};
crow.Graph.algorithm={};crow.Graph.defaultAlgorithm={};crow.Graph.fromTilePlane=function(a,b){if(!window.Effect||!window.Effect.Port)throw Error("EffectGames-specific extensions don't work anywhere else");if(!a)throw Error("tplane is required");if(typeof b!=="function")throw Error("callback not provided or not a function");for(var c=new crow.Graph,d=0,e=a.getMaxTileX();d<e;d++)for(var f=0,g=a.getMaxTileY();f<g;f++){var h=a.lookupTile(d,f),i=a.lookupTile(d,f,true);(h=b(h,i))&&c.addNode(h)}return c};
crow.Graph.fromArray=function(a,b){crow.assert(a instanceof Array,crow.assert.InvalidArgumentType("Array"));for(var c=new crow.Graph,d,e=0,f=0;f<a.length;f++){d=0;for(var g=a[f],h=0;h<g.length;h++){var i=g.charAt(h);(i=b(d,e,i))&&c.addNode(i);d++}e++}return c};crow.Graph.registerAlgorithm=function(a){var b=a.alias;if(!b)throw Error("No alias found for algorithm");crow.Graph.algorithm[b]=a};
crow.Graph._lookupAlgorithm=function(a){var b=typeof a;if(b==="string"){if(b=crow.Graph.algorithm[a])return b;throw Error("Algorithm `"+a+"` not found");}else if(b==="object"||b==="undefined")if(b=crow.AlgorithmResolver.getAlgorithm(a))return b;return null};crow.GraphUtil={distance:{euclidean:function(a,b){return Math.sqrt(Math.pow(a,2)+Math.pow(b,2))},manhattan:function(a,b){return Math.abs(a)+Math.abs(b)},chebyshev:function(a,b){return Math.max(Math.abs(a),Math.abs(b))},one:function(){return 1}}};
crow.GraphUtil.distance.pythagoras=crow.GraphUtil.distance.euclidean;crow.GraphUtil.distance.maximum=crow.GraphUtil.distance.chebyshev;crow.GraphUtil.distance.manhattan8=crow.GraphUtil.distance.chebyshev;crow.AlgorithmResolver=new function(){this.getAlgorithm=function(a){return this.getAlgorithms(a).dequeue()};this.getAlgorithms=function(a){a||(a={});if(typeof a.heuristics_allowed==="undefined")a.heuristics_allowed=true;var b=crow.Graph.algorithm,c=new crow.structs.BucketPriorityQueue(crow.structs.BucketPriorityQueue.REVERSE_KEY_COMPARATOR),d;for(d in b){var e=b[d],f=e.attributes;if(f){var g=0;if(typeof a.min_speed!=="undefined"&&a.min_speed>f.min_speed)g-=Infinity;else g+=f.min_speed;if(a.moving_start&&
!f.moving_start||a.moving_goal&&!f.moving_goal||a.unstable_graph&&!f.unstable_graph||!a.heuristics_allowed&&f.heuristics_allowed||a.goal_is_node&&!f.goal_is_node||a.goal_is_callback&&!f.goal_is_callback)g-=Infinity;g>-Infinity&&c.enqueue(g,e)}}return c}};crow.algorithm={};crow.algorithm.ShortestPathAlgorithm=function(){};crow.algorithm.ShortestPathAlgorithm.prototype=new crow.Algorithm;crow.algorithm.ShortestPathAlgorithm.prototype.findPath=function(){this.wrapperNode=new crow.Algorithm.NodeMap};crow.Node=function(a){a||(a=""+Math.random());this.id=a};crow.Node.prototype.distanceAlgorithm=crow.GraphUtil.distance.manhattan;crow.Node.prototype.distanceToGoal=function(){throw Error("This method (either distanceToGoal or distanceToNeighbor) was called, but is not implemented.  You must override this method in your own class to determine the distance between nodes.");};crow.Node.prototype.distanceToNeighbor=function(){throw Error("distanceToNeighbor must be overridden");};
crow.Node.prototype.getNeighbors=function(){throw Error("This method (getNeighbors) was called, but is not implemented.  You need to implement it so that the algorithm knows how to find the nodes reachable from the current node.");};crow.GridNode=function(a){crow.Node.apply(this);if(a){this.x=a[0];this.y=a[1]}this._initialized=this.isBlank=false};crow.GridNode.prototype=new crow.Node;
crow.GridNode.prototype._initialize=function(){if(!this._initialized){this._initialized=true;var a=this.getX(),b=this.getY();if(typeof a!=="number")throw Error("Node must have a valid x coord");if(typeof b!=="number")throw Error("Node must have a valid y coord");a=Math.floor(a);b=Math.floor(b);this.x=a;this.y=b;this.generateId();delete this.getX;delete this.getY;if(this.distanceToNeighbor==crow.Node.prototype.distanceToNeighbor)this.distanceToNeighbor=this.distanceToGoal}};
crow.GridNode.prototype.getX=function(){return this.x};crow.GridNode.prototype.getY=function(){return this.y};crow.GridNode.prototype.distanceToGoal=function(a){return this.distanceAlgorithm(this.x-a.x,this.y-a.y)};crow.GridNode.prototype.generateId=function(){return this.id=this.x+"_"+this.y};
crow.GridNode.prototype.getNeighbors=function(a,b,c){var d=this.x,e=this.y,f=[];f.push(a.getNode(d+1,e));b&&f.push(a.getNode(d+1,e+1));f.push(a.getNode(d,e+1));b&&f.push(a.getNode(d-1,e+1));f.push(a.getNode(d-1,e));b&&f.push(a.getNode(d-1,e-1));f.push(a.getNode(d,e-1));b&&f.push(a.getNode(d+1,e-1));a=[];for(b=0;b<f.length;b++)if(d=f[b])a.push(d);else c&&a.push(null);return a};crow.BaseNode=crow.GridNode;crow.algorithm.Path=function(a){this.nodes=a.nodes;this.start=a.start;this.end=this.goal=a.goal;this.length=a.length;this.found=a.found;this.actor=this.graph=this.algorithm=null;this._baked=true;if(a.baked===false){this._baked=false;this.algorithm=a.algorithm;this.graph=a.graph;this.actor=a.actor;if(this.graph){this.graph.validator.addEventListener("invalidatePoint",this._invalidatePoint,null,this);this.graph.validator.addEventListener("invalidateRegion",this._invalidateRegion,null,this)}}};
crow.algorithm.Path.prototype.copyTo=function(a){for(var b in this)a[b]=this[b]};crow.algorithm.Path.prototype._invalidatePoint=function(a){this._baked||this.algorithm._invalidatePoint(this,a)};crow.algorithm.Path.prototype._invalidateRegion=function(a){this._baked||this.algorithm._invalidateRegion(this,a)};
crow.algorithm.Path.prototype.advanceTo=function(a){crow.assert(typeof a==="number"||a instanceof crow.BaseNode,crow.assert.InvalidArgumentType("number or crow.BaseNode"));if(typeof a==="number"){crow.assert(a>=0&&a<this.nodes.length,crow.assert.IndexOutBounds(a));return this.advanceTo(this.nodes[a])}else{var b=a.x,c=a.y,d,e=false;for(d=0;d<this.nodes.length;d++){var f=this.nodes[d];if(f.x===b&&f.y===c){e=true;break}}if(e){this.start=a;this.found=false;this.algorithm.moveStart&&this.algorithm.moveStart(this,
a)}else{this.nodes=[a];this.found=false;this.end=null}}};crow.algorithm.Path.prototype.moveTarget=function(a){if(!this.algorithm.klass.attributes.moving_goal)throw Error(crow.assert.IllegalMethodCall("moveGoal","This method is intended only to be used with algorithms that support moving targets."));this.goal=a;this.found=false;this.algorithm.moveTarget&&this.algorithm.moveTarget(this,a)};crow.algorithm.Path.prototype.getNextNode=function(){return this.nodes[1]};
crow.algorithm.Path.prototype.continueCalculating=function(a){if(this._baked)throw Error("Can't continue calculating a baked path.  Either pass {baked: false} to findGoal, or don't call .bake() on this path yet.");if(this.found)return true;return this.algorithm.continueCalculating(this,a)};
crow.algorithm.Path.prototype.bake=function(){this._baked=true;if(this.graph){this.graph.validator.removeEventListener("invalidatePoint",this._invalidatePoint);this.graph.validator.removeEventListener("invalidateRegion",this._invalidateRegion);this.graph=null}this.actor=this.algorithm=null};crow.algorithm.AStarAlgorithm={};
(function(){crow.algorithm.AStarAlgorithm=function(a){this.klass=crow.algorithm.AStarAlgorithm;this.graph=a};crow.algorithm.AStarAlgorithm.prototype=new crow.algorithm.ShortestPathAlgorithm;crow.algorithm.AStarAlgorithm.prototype.findPath=function(a,b,c){crow.algorithm.ShortestPathAlgorithm.prototype.findPath.apply(this,arguments);if(typeof b==="function")throw Error("A* doesn't support using a callback to determine the goal");this._wrapperNode=new crow.Algorithm.NodeMap;c||(c={});var d=c.actor;this.start=
a;this.goal=b;this.opts=c;a=this._getWrapperNode(a);this.openSet=new crow.structs.BucketPriorityQueue;this.openSet.enqueue(0,a);a.g=0;a.h=a.innerNode.distanceToGoal(b,d);for(var e=false,f;f=this.openSet.dequeue();){if(f.innerNode===b){e=true;break}else if(f.expanded)continue;f.expanded=true;for(var g=f.innerNode.getNeighbors(this.graph),h=0;h<g.length;h++){var i=this._getWrapperNode(g[h]);if(!i.expanded){var j=f.g+f.innerNode.distanceToNeighbor(i.innerNode,d);if(j!=Infinity)if(!this.openSet.contains(i)||
j<i.g){i.parent=f;i.g=j;var k=i.innerNode.distanceToGoal(b,d);i.f=j+k;this.openSet.enqueue(i.f,i)}}}}f=[];d={nodes:f,start:a.innerNode,goal:b,length:null,recalculate:this.recalculate,algorithm:this,graph:c.graph,baked:c.baked||typeof c.baked==="undefined"&&!c.limit,actor:d};if(e){e=this._getWrapperNode(b);f.unshift(e.innerNode);for(g=e.parent;g;){f.unshift(g.innerNode);g=g.parent}d.end=e.innerNode;d.length=e.g;d.found=true}else{d.end=null;d.length=Infinity;d.found=false}return new crow.algorithm.Path(d)};
crow.algorithm.AStarAlgorithm.WrapperNode=function(a){this.innerNode=a;this.expanded=false;this.parent=null;this.g=Infinity;this.f=this.h=null};crow.algorithm.AStarAlgorithm.prototype._getWrapperNode=crow.Algorithm.wrapperNodeGetterTemplate(crow.algorithm.AStarAlgorithm.WrapperNode);crow.algorithm.AStarAlgorithm.attributes={min_speed:2,moving_start:false,moving_goal:false,unstable_graph:false,heuristics_allowed:true,goal_is_node:true,goal_is_callback:false};crow.algorithm.AStarAlgorithm.alias="a*";
crow.Graph.registerAlgorithm(crow.algorithm.AStarAlgorithm)})();crow.algorithm.BasicTraversalAlgorithm={};
(function(){crow.algorithm.BasicTraversalAlgorithm=function(a){this.klass=crow.algorithm.BasicTraversalAlgorithm;this.graph=a};crow.algorithm.BasicTraversalAlgorithm.prototype=new crow.algorithm.ShortestPathAlgorithm;crow.algorithm.BasicTraversalAlgorithm.prototype.findPath=function(a,b,c){crow.algorithm.ShortestPathAlgorithm.prototype.findPath.apply(this,arguments);if(typeof c=="undefined")c={};a=this._getWrapperNode(a);a.distance=0;this.actor=c.actor;for(var d=c.filter,e=false,f=[a],g=[],h;h=this.getNext(f);){h.pending=
false;h.expanded=true;g.push(h.innerNode);if(h.innerNode==b){e=true;break}var i=h.innerNode.getNeighbors(this.graph);if(c.random)i=i.shuffle();for(var j=0;j<i.length;j++){var k=this._getWrapperNode(i[j]);if(!(k.expanded||k.pending))if(h.innerNode.distanceToNeighbor(k.innerNode,this.actor)<Infinity&&(!d||d.call(this,k))){this.addNext(f,k);k.pending=true;k.parent=h;k.distance=h.distance+1}}}this.start=a;this.goal=b;this.list=g;return this.resolveResults(e)};crow.algorithm.BasicTraversalAlgorithm.prototype.getNext=
function(){throw Error("must implement");};crow.algorithm.BasicTraversalAlgorithm.prototype.addNext=function(a,b){a.push(b)};crow.algorithm.BasicTraversalAlgorithm.prototype.resolveResults=function(a){var b=[],c={nodes:b,start:this.start.innerNode,goal:this.goal,algorithm:this,graph:this.graph,baked:true,actor:this.actor,found:a};if(a){a=this._getWrapperNode(this.goal);b.unshift(a.innerNode);for(var d=a.parent;d;){b.unshift(d.innerNode);d=d.parent}c.end=a.innerNode;c.length=a.distance}else{c.end=
null;c.length=Infinity}b=new crow.algorithm.Path(c);b.allNodes=this.list;return b};crow.algorithm.BasicTraversalAlgorithm.WrapperNode=function(a){this.innerNode=a;this.pending=this.expanded=false;this.parent=null;this.distance=Infinity};crow.algorithm.BasicTraversalAlgorithm.prototype._getWrapperNode=crow.Algorithm.wrapperNodeGetterTemplate(crow.algorithm.BasicTraversalAlgorithm.WrapperNode)})();crow.algorithm.BFSAlgorithm=function(a){this.klass=crow.algorithm.BFSAlgorithm;this.graph=a};crow.algorithm.BFSAlgorithm.prototype=new crow.algorithm.BasicTraversalAlgorithm;crow.algorithm.BFSAlgorithm.prototype.getNext=function(a){return a.shift()};crow.algorithm.BFSAlgorithm.alias="bfs";crow.Graph.registerAlgorithm(crow.algorithm.BFSAlgorithm);crow.algorithm.SearchAlgorithm=function(){};crow.algorithm.SearchAlgorithm.prototype=new crow.Algorithm;crow.algorithm.SearchAlgorithm.prototype.search=function(){this.wrapperNode=new crow.Algorithm.NodeMap};crow.algorithm.BFSBasicAlgorithm=function(a){this.klass=crow.algorithm.BFSBasicAlgorithm;this.graph=a};crow.algorithm.BFSBasicAlgorithm.prototype=new crow.algorithm.SearchAlgorithm;crow.algorithm.BFSBasicAlgorithm.prototype.search=function(a,b){return(new crow.algorithm.BFSAlgorithm(this.graph)).findPath(a,null,b).allNodes};crow.algorithm.BFSBasicAlgorithm.alias="bfs_basic";crow.Graph.registerAlgorithm(crow.algorithm.BFSBasicAlgorithm);crow.algorithm.DFSAlgorithm=function(a){this.klass=crow.algorithm.DFSAlgorithm;this.graph=a};crow.algorithm.DFSAlgorithm.prototype=new crow.algorithm.BasicTraversalAlgorithm;crow.algorithm.DFSAlgorithm.prototype.getNext=function(a){return a.pop()};crow.algorithm.DFSAlgorithm.alias="dfs";crow.Graph.registerAlgorithm(crow.algorithm.DFSAlgorithm);crow.algorithm.DijkstraAlgorithm=function(a){this.klass=crow.algorithm.DijkstraAlgorithm;this.graph=a};crow.algorithm.DijkstraAlgorithm.prototype=new crow.algorithm.ShortestPathAlgorithm;
crow.algorithm.DijkstraAlgorithm.prototype.findPath=function(a,b,c){crow.algorithm.ShortestPathAlgorithm.prototype.findPath.apply(this,arguments);this.visitedList=[];this.start=a;this.goal=b;this.opts=c||{};if(c.limit)throw Error("Dijkstra's doesn't support the `limit` option.");this.actor=c.actor;this._getWrapperNode(a).distance=0;var d,e;if(typeof b==="function"){this.mainLoop(a);d=this.determineClosestEndNode(b);e=!!d}else{e=this.mainLoop(a,b);d=this._getWrapperNode(b)}var f=[];if(d.distance<Infinity){f.unshift(d.innerNode);
for(var g=d.previous;g;){f.unshift(g.innerNode);g=g.previous}}return new crow.algorithm.Path({nodes:f,start:a,goal:b,end:e?d.innerNode:null,length:e?d.distance:Infinity,found:e,algorithm:this,graph:c.graph,baked:c.baked||typeof c.baked==="undefined"&&!c.limit,actor:this.actor})};crow.algorithm.DijkstraAlgorithm.prototype.determineClosestEndNode=function(a){for(var b,c=Infinity,d=0;d<this.visitedList.length;d++){var e=this.visitedList[d];if(a.call(e.innerNode)){var f=e.distance;if(f<c){b=e;c=f}}}return b};
crow.algorithm.DijkstraAlgorithm.prototype.mainLoop=function(a,b){var c=new crow.Algorithm.PriorityQueue;for(a=this._getWrapperNode(a);a!=null;){for(var d=a.innerNode.getNeighbors(this.graph),e=0;e<d.length;e++){var f=this._getWrapperNode(d[e]);if(!f.visited){var g=a.distance+a.innerNode.distanceToNeighbor(f.innerNode,this.actor),h=f.distance;if(g<h){f.distance=g;f.previous=a;h=g}h<Infinity&&c.enqueue(h,f)}}a.visited=true;this.visitedList.push(a);if(a.innerNode===b)return true;a=c.dequeue()}return false};
crow.algorithm.DijkstraAlgorithm.WrapperNode=function(a){this.innerNode=a;this.visited=false;this.previous=null;this.distance=Infinity};crow.algorithm.DijkstraAlgorithm.prototype._getWrapperNode=crow.Algorithm.wrapperNodeGetterTemplate(crow.algorithm.DijkstraAlgorithm.WrapperNode);crow.algorithm.DijkstraAlgorithm.attributes={min_speed:-2,moving_start:false,moving_goal:false,unstable_graph:false,heuristics_allowed:false,goal_is_node:true,goal_is_callback:true};
crow.algorithm.DijkstraAlgorithm.alias="dijkstra";crow.Graph.registerAlgorithm(crow.algorithm.DijkstraAlgorithm);crow.algorithm.FRAStarAlgorithm=function(a){this.klass=crow.algorithm.FRAStarAlgorithm;this.graph=a};crow.algorithm.FRAStarAlgorithm.prototype=new crow.algorithm.ShortestPathAlgorithm;crow.algorithm.FRAStarAlgorithm.prototype._invalidatePoint=function(){crow.Algorithm.prototype._invalidatePoint.apply(this,arguments);this.reset()};
crow.algorithm.FRAStarAlgorithm.prototype.reset=function(){this.wrapperNode=new crow.Algorithm.NodeMap;this.start=this._getWrapperNode(this.start.innerNode);this.goal=this._getWrapperNode(this.goal.innerNode);this.iteration=1;this.start.initialize();this.start.g=0;this.evaluatedList=[];this.openSet=new crow.structs.BucketPriorityQueue;this.openSet.enqueue(0,this.start);this.state=1};crow.algorithm.FRAStarAlgorithm.prototype.ComputePriority=function(a){return a.g+a.innerNode.distanceToGoal(this.goal.innerNode)};
crow.algorithm.FRAStarAlgorithm.prototype.TestClosedList=function(a){return a==this.start||!!(a.expanded&&a.parent)};
crow.algorithm.FRAStarAlgorithm.prototype.ComputeShortestPath=function(){for(;node=this.openSet.dequeue();)if(!node.expanded){node.expanded=true;for(var a=node.innerNode.getNeighbors(this.graph,this.neighbors),b=0;b<a.length;b++){var c=this._getWrapperNode(a[b]);if(!this.TestClosedList(c)){c.initialize();var d=node.g+node.innerNode.distanceToNeighbor(c.innerNode);if(d<c.g){c.g=d;c.parent=node;this.openSet.enqueue(this.ComputePriority(c),c)}}}if(node==this.goal)return true}return false};
crow.algorithm.FRAStarAlgorithm.prototype.UpdateParent=function(a){var b=this.cell,c=b.innerNode.getNeighbors(this.graph,this.diagonals);a||(c=c.reverse());var d=b.parent;a=-1;for(var e=0;e<c.length;e++)if(c[e]==d){a=e;break}if(a>=0)for(e=0;e<c.length;e++){d=this._getWrapperNode(c[(e+a)%c.length]);if(d.g==b.g+b.innerNode.distanceToNeighbor(d.innerNode)&&this.TestClosedList(d)){d.parent=b;this.cell=d;return true}}return false};
crow.algorithm.FRAStarAlgorithm.prototype.Step2=function(){for(this.cell=this.start;this.UpdateParent(false););for(this.cell=this.start;this.UpdateParent(true););};
crow.algorithm.FRAStarAlgorithm.prototype.Step3=function(){this.start.parent=null;for(var a=this.start,b=this.previousStart,c=this._getWrapperNode,d=this,e=(new crow.algorithm.BFSBasicAlgorithm(this.graph)).search(this.previousStart.innerNode,{filter:function(h){h=c.call(d,h).ancestors();return h.indexOf(b)>=0&&h.indexOf(a)<0}}),f=0;f<e.length;f++){var g=this._getWrapperNode(e[f]);g.parent=null;this.openSet.remove(g)}};
crow.algorithm.FRAStarAlgorithm.prototype.FindPerimeter=function(a,b){var c=[b],d=a.innerNode.getNeighbors(this.graph,this.diagonals,true),e;for(e=0;e<d.length;e++){var f=d[e];if(f==b.innerNode)break}f=a;for(var g=0;g<d.length;g++){var h=(e+g)%d.length;if(f=d[h]){f=this._getWrapperNode(f);if(this.TestClosedList(f))if(f==a)break;else{f=f;d=f.innerNode.getNeighbors(this.graph,this.diagonals,true);e=h+3;g=-1}else c[c.length-1]!=f&&c.push(f)}}return c};
crow.algorithm.FRAStarAlgorithm.prototype.Step5=function(){for(var a=this.FindPerimeter(this.start,this.anchor),b=0;b<a.length;b++){var c=a[b];this.openSet.enqueue(this.ComputePriority(c),c)}var d=this;this.openSet.each(function(f){f.initialize()});var e=[];this.openSet.each(function(f){for(var g=f.innerNode.getNeighbors(d.graph,d.diagonals),h=0;h<g.length;h++){var i=d._getWrapperNode(g[h]),j=i.g+i.innerNode.distanceToNeighbor(f.innerNode);if(d.TestClosedList(i)&&f.g>j){f.g=j;f.parent=i;e.push(f)}}});
for(b=0;b<e.length;b++){a=e[b];this.openSet.enqueue(this.ComputePriority(a),a)}};crow.algorithm.FRAStarAlgorithm.prototype.findPath=function(a,b,c){c||(c={});crow.algorithm.ShortestPathAlgorithm.prototype.findPath.apply(this,arguments);a=this._getWrapperNode(a);b=this._getWrapperNode(b);this.start=a;this.goal=b;this.opts=c;this.reset();var d=this.resolveResults(this.opts,false);this.continueCalculating(d);return d};
crow.algorithm.FRAStarAlgorithm.prototype.resolveResults=function(a,b){a||(a={});var c;c=b?{nodes:this.goal.ancestors(true).concat(this.goal.innerNode),start:this.start.innerNode,goal:this.goal.innerNode,found:true,length:this.goal.g,algorithm:this,graph:a.graph,baked:a.baked||typeof a.baked==="undefined",actor:a.actor}:{nodes:[],start:this.start.innerNode,goal:this.goal.innerNode,found:false,length:Infinity,algorithm:this,graph:a.graph,baked:a.baked||typeof a.baked==="undefined",actor:a.actor};return new crow.algorithm.Path(c)};
crow.algorithm.FRAStarAlgorithm.prototype.updateStart=function(a){for(var b=false,c=0;c<a.nodes.length;c++)if(a.nodes[c]==this.start.innerNode){a.nodes.splice(0,c);b=true;break}if(b){for(c=b=0;c<a.nodes.length-1;c++)b+=a.nodes[c].distanceToNeighbor(a.nodes[c+1]);a.length=b}else throw Error("Present (start) position not found on path!  FRA* only works if this agent follows the path towards the target.");};
crow.algorithm.FRAStarAlgorithm.prototype.continueCalculating=function(a){this.start=this._getWrapperNode(this.start);this.goal=this._getWrapperNode(this.goal);if(this.previousStart)this.previousStart=this._getWrapperNode(this.previousStart);if(this.previousGoal)this.previousGoal=this._getWrapperNode(this.previousGoal);for(;;)switch(this.state){case 1:if(this.start==this.goal)this.state=true;else{var b=this.ComputeShortestPath(),c=this.resolveResults(null,b);a.found=b;a.nodes=c.nodes;a.length=this.goal.g;
if(b){this.openListIncomplete=false;this.state=3}else this.state=false}break;case 3:this.state=this.TestClosedList(this.goal)?4:5;break;case 4:if(this.start!=this.goal)for(b=0;b<a.nodes.length;b++)if(a.nodes[b]==this.goal.innerNode){this.updateStart(a);return true}if(this.start==this.goal)this.state=true;else{if(this.newTarget){this.previousGoal=this.goal;this.goal=this._getWrapperNode(this.newTarget);this.newTarget=null}if(!this.previousStart)this.previousStart=this.start;if(this.start!=this.previousStart){this.Step2();
this.anchor=this.start.parent;this.Step3();this.openListIncomplete=true}this.state=3}break;case 5:if(this.openListIncomplete){this.iteration++;this.Step5()}this.state=1;break;case true:a.found=true;a.nodes=[a.goal];a.length=0;return true;case false:a.found=false;a.nodes=[];a.length=Infinity;return false}};crow.algorithm.FRAStarAlgorithm.prototype.moveStart=function(a,b){this.previousStart=this.start;this.start=b};
crow.algorithm.FRAStarAlgorithm.prototype.moveTarget=function(a,b){this.previousGoal=this.goal;this.goal=b};crow.algorithm.FRAStarAlgorithm.WrapperNode=function(a){this.innerNode=a;this.generatedIteration=0;this.expanded=false;this.parent=this.g=null};crow.algorithm.FRAStarAlgorithm.prototype._getWrapperNode=crow.Algorithm.wrapperNodeGetterTemplate(crow.algorithm.FRAStarAlgorithm.WrapperNode);
crow.algorithm.FRAStarAlgorithm.WrapperNode.prototype.initialize=function(){var a=this.algorithm.iteration;if(this.generatedIteration!=a){this.g=Infinity;this.generatedIteration=a;this.expanded=false}};crow.algorithm.FRAStarAlgorithm.WrapperNode.prototype.ancestors=function(a){for(var b=[],c=this.parent;c;){b.unshift(a?c.innerNode:c);c=c.parent}return b};
crow.algorithm.FRAStarAlgorithm.attributes={min_speed:2,moving_start:true,moving_goal:true,unstable_graph:false,heuristics_allowed:true,goal_is_node:true,goal_is_callback:false};crow.algorithm.FRAStarAlgorithm.alias="fra*";crow.Graph.registerAlgorithm(crow.algorithm.FRAStarAlgorithm);crow.algorithm.LinearAlgorithm=function(a){this.klass=crow.algorithm.LinearAlgorithm;this.graph=a};crow.algorithm.LinearAlgorithm.prototype=new crow.algorithm.SearchAlgorithm;crow.algorithm.LinearAlgorithm.prototype.search=function(a,b){b||(b={});var c,d=this.graph.getNodes();if(b.filter){c=[];for(var e=0;e<d.length;e++){var f=d[e];b.filter.call(f)&&c.push(f)}}else c=d;return c};crow.algorithm.LinearAlgorithm.alias="linear";crow.Graph.registerAlgorithm(crow.algorithm.LinearAlgorithm);crow.structs.NDArray=function(a){this.arr=[];this.dimensions=a};crow.structs.NDArray.prototype.add=function(a){if(arguments.length-1!=this.dimensions)throw Error(crow.assert.IncorrectArgumentCount(arguments.length,this.dimensions+1));for(var b=this.arr,c=b,d=arguments.length,e=1;e<d-1;e++){c=b[arguments[e]];if(typeof c==="undefined")c=b[arguments[e]]=[];b=c}c[arguments[d-1]]=a};
crow.structs.NDArray.prototype.get=function(){if(arguments.length!=this.dimensions)throw new crow.assert.IncorrectArgumentCount(arguments.length,this.dimensions);for(var a=this.arr,b=0;b<arguments.length&&typeof a!=="undefined";b++)a=a[arguments[b]];return a};crow.structs.NDArray.prototype.each=function(a){for(var b=0;b<this.arr.length;b++){var c=this.arr[b];typeof c!=="undefined"&&this._each(a,c,[b])}};
crow.structs.NDArray.prototype._each=function(a,b,c){if(b instanceof Array&&c.length<=this.dimensions)for(var d=0;d<b.length;d++){var e=c.slice(0).concat(d),f=b[d];typeof f!=="undefined"&&this._each(a,f,e)}else{c.unshift(b);a.apply(this,c)}};crow.algorithm.LPAStarAlgorithm=function(a){this.klass=crow.algorithm.LPAStarAlgorithm;this.graph=a};crow.algorithm.LPAStarAlgorithm.prototype=new crow.algorithm.ShortestPathAlgorithm;crow.algorithm.LPAStarAlgorithm.prototype._CalculateKey=function(a){var b=Math.min(a.g,a.rhs);return[b+a.innerNode.distanceToGoal(this.goal.innerNode),b]};
crow.algorithm.LPAStarAlgorithm.prototype._UpdateVertex=function(a){if(a!=this.start){for(var b=a.innerNode.getNeighbors(this.graph,this.diagonals),c=Infinity,d=0;d<b.length;d++){var e=this._getWrapperNode(b[d]);e=e.g+a.innerNode.distanceToNeighbor(e.innerNode);if(e<c)c=e}a.rhs=c}this.U.remove(a);a.g!=a.rhs&&this.U.enqueue(this._CalculateKey(a),a)};crow.algorithm.LPAStarAlgorithm.prototype.keyComp=function(a,b){if(a[0]<b[0]||a[0]==b[0]&&a[1]<b[1])return-1;if(a[0]==b[0]&&a[1]==b[1])return 0;return 1};
crow.algorithm.LPAStarAlgorithm.prototype.updateNeighbors=function(a){a=a.innerNode.getNeighbors(this.graph,this.diagonals);for(var b=0;b<a.length;b++)this._UpdateVertex(this._getWrapperNode(a[b]))};crow.algorithm.LPAStarAlgorithm.prototype.debugGraph=function(){};
crow.algorithm.LPAStarAlgorithm.prototype.findPath=function(a,b,c){if(typeof b==="function")throw Error("LPA* doesn't support using a callback to determine the goal");c||(c={});this._wrapperNode=new crow.Algorithm.NodeMap;this.start=this._getWrapperNode(a);this.goal=this._getWrapperNode(b);this.diagonals=c.diagonals;this.U=new crow.structs.BucketPriorityQueue(this.keyComp);this.start.rhs=0;this.U.enqueue(this._CalculateKey(this.start),this.start);this.mainLoop();a=this.resolveResults();return new crow.algorithm.Path({nodes:a.nodes,
start:this.start.innerNode,goal:this.goal.innerNode,found:a.found,length:a.length,recalculate:this.recalculate,algorithm:this,baked:c.baked||typeof c.baked==="undefined"&&!c.limit,graph:c.graph})};crow.algorithm.LPAStarAlgorithm.prototype.mainLoop=function(){for(;this.U.length&&(this.keyComp(this.U.peekKey(),this._CalculateKey(this.goal))<0||this.goal.rhs!=this.goal.g);){var a=this.U.dequeue();if(a.g>a.rhs){a.g=a.rhs;this.updateNeighbors(a)}else{a.g=Infinity;this.updateNeighbors(a);this._UpdateVertex(a)}}};
crow.algorithm.LPAStarAlgorithm.prototype.resolveResults=function(){var a=[],b=this.goal,c=0,d=0;if(this.graph)failSafeMaximum=this.graph.width*this.graph.height;for(;b!=this.start&&b;){a.unshift(b.innerNode);for(var e=b.innerNode.getNeighbors(this.graph,this.diagonals),f=Infinity,g=null,h=0,i=0,j=0;j<e.length;j++){var k=this._getWrapperNode(e[j]);h=b.innerNode.distanceToNeighbor(k.innerNode);var m=k.g+h;if(m<f){f=m;g=k;i=h}}if(b=g)c+=i;d++;if(d>=Infinity)throw Error("resolveResults won't terminate");
}(b=b==this.start)||(a=[]);a.unshift(this.start.innerNode);return{nodes:a,length:c,found:b}};crow.algorithm.LPAStarAlgorithm.prototype.recalculate=function(){var a=this.algorithm;return a.findPath(a.start,a.goal,a.opts)};
crow.algorithm.LPAStarAlgorithm.prototype._invalidatePoint=function(a,b){var c=b.x,d=b.y;if(!a.invalidatedPoints)a.invalidatedPoints=new crow.structs.NDArray(2);a.invalidatedPoints.add(true,c,d);c=a.graph.getNode(c,d,true).getNeighbors(a.graph,a.algorithm.diagonals);for(d=0;d<c.length;d++){var e=c[d];a.invalidatedPoints.add(true,e.x,e.y)}a.found=false};
crow.algorithm.LPAStarAlgorithm.prototype.continueCalculating=function(a){if(a.invalidatedPoints){var b=this,c=this._getWrapperNode;a.invalidatedPoints.each(function(e,f,g){(e=b.graph.getNode(f,g))&&b._UpdateVertex(c.call(b,e))});this.mainLoop();a.invalidatedPoints=new crow.structs.NDArray(2);var d=this.resolveResults();a.nodes=d.nodes;a.length=d.length;a.found=d.found}return a.found};
crow.algorithm.LPAStarAlgorithm.prototype._getWrapperNode=function(a){var b=this._wrapperNode.get(a);if(b)return b;b=new crow.algorithm.LPAStarAlgorithm.WrapperNode(a);this._wrapperNode.set(a,b);return b};crow.algorithm.LPAStarAlgorithm.WrapperNode=function(a){this.innerNode=a;this.g=this.rhs=Infinity};crow.algorithm.LPAStarAlgorithm.attributes={min_speed:0,moving_start:false,moving_goal:false,unstable_graph:true,heuristics_allowed:true,goal_is_node:true,goal_is_callback:false};
crow.algorithm.LPAStarAlgorithm.alias="lpa*";crow.Graph.registerAlgorithm(crow.algorithm.LPAStarAlgorithm);crow.All={};
